ObselBundle\Model\ObselCategory:
    type: entity
    repositoryClass: ObselBundle\Repository\ObselCategoryRepository
    table: obsel_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100