# ObselBundle/Ressources/config/doctrine-mapping/Obsel.orm.yml
ObselBundle\Ressources\config\doctrine-mapping\Obsel:
    type: entity
    repositoryClass: ObselBundle\Repository\ObselRepository
    table: obsel
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        startsAt:
            type: datetime
        endsAt:
            type: datetime
        subject:
            type: string
            length: 255
        metadata:
            type: text