# ObselBundle/Ressources/config/doctrine-mapping/Obsel.orm.yml
ObselBundle\Model\Obsel:
    type: entity
    repositoryClass: ObselBundle\Repository\ObselRepository
    table: obsel
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        subject:
            type: string
            length: 255
        metadata:
            type: text
        startsAt:
            type: datetime
            column: starts_at
        endsAt:
            type: datetime
            column: ends_at
