<?php

namespace ObselBundle\Repository;

/**
 * ObselCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObselCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
