<?php

namespace ObselBundle\Repository;

/**
 * ObselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObselRepository extends \Doctrine\ORM\EntityRepository
{
}
